### ISSUE TITLE
Limited Output?

### ISSUE THREAD

**Issue by MinchinWeb** [jonathaneunice/ansiwrap#1]
I'm trying to figure out a way to print a string with ansi codes, but only the first, say 300 "normal" characters worth. Is there an easy way to do this with your library? 

P.S. What license is your library under?

Thanks!

**Comment by jonathaneunice** [comment]
`ansiwrap` is licensed under Apache 2.0. That is stated in `setup.py`. I just added a `LICENSE.txt` to further clarify.

Have also pushed a new version, 0.8.1, with clarified docs. [See them on PyPI](https://pypi.python.org/pypi/ansiwrap). But to cut to the chase, yes. That's exactly the sort of thing that the module does. In your case, try:

    from ansiwrap import shorten
    s = '...string with ansi codes...'
    print(shorten(s, 300, placeholder='...'))

And the string will be shortened to 300 real characters, ignoring ANSI codes in the length calculation.
